build: update build

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -2,24 +2,25 @@ FROM node:20.14.0-alpine3.20 AS builder
 
 WORKDIR /app
 
-
 COPY package*.json ./
 COPY client/package*.json client/
 COPY server/package*.json server/
 
 RUN npm ci
 
-COPY server/ ./server/
+COPY . .  
 
 WORKDIR /app/server
 
 RUN npm run build
 
-RUN npm run migrate:latest:prod
+RUN npm run migrate:latest:prod || echo "Migrations failed, continuing..."
 
 EXPOSE 3000
 
 ENV HOST 0.0.0.0
 ENV PORT 3000
+
+RUN ls -l /app/server/dist || echo "No compiled server files found!"
 
 CMD ["node", "dist/index.js"]
